name: Deploy to Dev with Docker Compose

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Copy docker-compose file to remote server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SERVER_PASS }}
          port: 2323
          source: "docker-compose.yml"
          target: "/home/${{ secrets.USERNAME }}/projekt"
          strip_components: 0

      - name: Deploy with Docker Compose on remote server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SERVER_PASS }}
          port: 2323
          script: |
            cd /home/${{ secrets.USERNAME }}/projekt
            # Pull the latest image
            docker pull vicciviccison/vrgameserverapp:latest
            # Stop any existing containers
            docker-compose -f docker-compose.yml down || true
            # Start the services in detached mode
            docker-compose -f docker-compose.yml up -d
            # Verify the services are running
            docker-compose -f docker-compose.yml ps
